### PR TITLE
 Add linters file, index and stylesheet

### PR DESCRIPTION
**Pull request by dfizzkruah93**
Added linters file:  .hintrc file and .stylintrc file
Added index and stylesheet

### CODE REVIEW

**Review by Deepakdanger — CHANGES_REQUESTED** [review]
Hi @dfizzkruah93, 

Good job so far! 👏
There are some issues that you still need to work on to go to the next project but you are almost there!


## Required Changes ♻️
- [ ] Your live link is not working as mentioned in your readme, Please modify it or delete it. 
- [ ] In Readme, Getting started section should contain the code to run locally. Kindly add it, For ex:- `git clone https://github.com/dfizzkruah93/Hello_Microverse.git`
`cd Hello_Microverse`
- [ ] Please update the Author's description in your readme & remove Author2 as it is solo project.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by dfizzkruah93** [comment]
I believe this require change should be an optional suggestion. Yet it's true I suppose to update my README file but I think it suppose to fall under optional because this is my second trial and I do have only one more

**Review by Amrhub — APPROVED** [review]
# Approved 💯 ✅ 🥳 🎈 🎉 

Hi @dfizzkruah93, 👋🏻 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 




Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by dfizzkruah93** [comment]
Thanks for the review

**Pull request merged**
